"""Data-quality summary: a table for Power BI and a Markdown report for the repository."""

import pandas as pd

from . import config


def dq_summary(raw_rows: int, scoped_rows: int, clean: pd.DataFrame, quarantine: pd.DataFrame) -> pd.DataFrame:
    by_reason = quarantine["reason_code"].value_counts()
    rows = [
        ("Published requests, all directorates", raw_rows, "Source"),
        ("Water and Sanitation field work (in scope)", scoped_rows, "Scope"),
        ("Duplicate record (same notification number)", int(by_reason.get("DUPLICATE_RECORD", 0)), "Quarantined"),
        ("Completed before created", int(by_reason.get("NEGATIVE_DURATION", 0)), "Quarantined"),
        ("Clean requests", len(clean), "Kept"),
        ("Closed within 5 minutes (administrative closure)", int(clean["is_admin_closure"].sum()),
         "Kept; excluded from durations and completions"),
        ("Likely repeat report (same fault, hexagon and day)", int(clean["is_likely_repeat"].sum()),
         "Kept; flagged"),
        ("No location", int((~clean["is_located"]).sum()), "Kept; not on the map"),
        ("No section", int(clean["section"].isna().sum()), "Kept as '<branch> (unassigned)'"),
        ("Never completed", int(clean["completed_at"].isna().sum()), "Kept; open from creation onward"),
    ]
    return pd.DataFrame(rows, columns=["rule", "rows", "action"])


def write_markdown(summary: pd.DataFrame, checksums: dict[str, str], reconciles: bool) -> None:
    lines = [
        "# Data-quality report",
        "",
        "Generated by `uv run python -m pipeline.run`. Do not edit by hand.",
        "",
        "| Rule | Rows | Action |",
        "|---|---:|---|",
        *[f"| {r.rule} | {r.rows:,} | {r.action} |" for r in summary.itertuples()],
        "",
        f"**Reconciliation:** in-scope rows = clean rows + quarantined rows: "
        f"**{'PASS' if reconciles else 'FAIL'}**",
        "",
        "## Sources",
        "",
        "| File | SHA-256 |",
        "|---|---|",
        *[f"| [{name}]({config.SOURCES[name]}) | `{digest}` |" for name, digest in checksums.items()],
        "",
        "Published by the City of Cape Town. Timestamps are converted to SAST (Africa/Johannesburg).",
        "",
    ]
    config.DQ_REPORT.parent.mkdir(parents=True, exist_ok=True)
    config.DQ_REPORT.write_text("\n".join(lines), encoding="utf-8")
