"""Write the DAX tests in powerbi/dax-tests/ from the pipeline's reference values.

Each test is a DAX query that compares the Power BI measures with the numbers the pipeline
computed independently (data/processed/reference_values.json). Each returns one row:
the test name, the number of checks, how many passed, PASS or FAIL, and the first failure.

Usage: uv run python scripts/build_dax_tests.py   (after uv run python -m pipeline.run)
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE = ROOT / "data" / "processed" / "reference_values.json"
OUT = ROOT / "powerbi" / "dax-tests"
UNKNOWN_SUBURB = "Unknown suburb"


def text(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def number(value) -> str:
    return "BLANK ()" if value is None else repr(value)


def datatable(columns: list[tuple[str, str]], rows: list[list[str]]) -> str:
    header = ", ".join(f"{text(name)}, {kind}" for name, kind in columns)
    body = ",\n        ".join("{ " + ", ".join(row) + " }" for row in rows)
    return f"DATATABLE (\n        {header},\n        {{\n        {body}\n        }}\n    )"


def query(title: str, purpose: str, expected: str, actual_columns: str, ok: str, label: str) -> str:
    """A query that adds the Power BI values to the expected table and summarises the comparison."""
    return f"""// {title}
// {purpose}
// Generated by scripts/build_dax_tests.py from the pipeline's reference values. Do not edit by hand.
EVALUATE
VAR expected =
    {expected}
VAR compared =
    ADDCOLUMNS (
        expected,
{actual_columns}
    )
VAR checked = ADDCOLUMNS ( compared, "ok", {ok} )
VAR failures = FILTER ( checked, NOT [ok] )
RETURN
    ROW (
        "Test", {text(title)},
        "Checks", COUNTROWS ( checked ),
        "Passed", COUNTROWS ( checked ) - COUNTROWS ( failures ),
        "Result", IF ( ISEMPTY ( failures ), "PASS", "FAIL" ),
        "First failure", CONCATENATEX ( TOPN ( 1, failures, {label}, ASC ), {label} )
    )
"""


def same(actual: str, expected: str) -> str:
    """Equal within rounding, and blank exactly where the pipeline is blank."""
    return (f"IF ( ISBLANK ( {expected} ), ISBLANK ( {actual} ), "
            f"NOT ISBLANK ( {actual} ) && ABS ( {actual} - {expected} ) < 0.000001 )")


def at(measure: str, *filters: str) -> str:
    return f"CALCULATE ( {measure}, {', '.join(filters)} )"


def open_active_stuck(ref: dict) -> str:
    rows = [[text(d), str(v["open"]), str(v["active"]), str(v["stuck"])] for d, v in ref["as_at"].items()]
    return query(
        "Open Now, Active and Stuck",
        "Department totals at each reference date.",
        datatable([("As at", "DATETIME"), ("Open (pipeline)", "INTEGER"),
                   ("Active (pipeline)", "INTEGER"), ("Stuck (pipeline)", "INTEGER")], rows),
        "\n".join([
            f'        "Open", VAR d = [As at] RETURN {at("[Open Now]", "as_at[as_at_date] = d")},',
            f'        "Active", VAR d = [As at] RETURN {at("[Active]", "as_at[as_at_date] = d")},',
            f'        "Stuck", VAR d = [As at] RETURN {at("[Stuck]", "as_at[as_at_date] = d")}',
        ]),
        "[Open] = [Open (pipeline)] && [Active] = [Active (pipeline)] && [Stuck] = [Stuck (pipeline)]",
        'FORMAT ( [As at], "yyyy-mm-dd" )',
    )


def weekly_flow(ref: dict) -> str:
    rows = [[text(w["week_start"][:10]), str(w["requests_in"]), str(w["completions"]), str(w["net_change"])]
            for w in ref["weekly_flow"]]
    return query(
        "Requests In, Completions and Net Change by week",
        "Every Monday-to-Sunday week of 2020.",
        datatable([("Week", "DATETIME"), ("In (pipeline)", "INTEGER"),
                   ("Done (pipeline)", "INTEGER"), ("Net (pipeline)", "INTEGER")], rows),
        "\n".join([
            f'        "In", VAR w = [Week] RETURN {at("[Requests In]", "dim_date[week_start] = w")},',
            f'        "Done", VAR w = [Week] RETURN {at("[Completions]", "dim_date[week_start] = w")},',
            f'        "Net", VAR w = [Week] RETURN {at("[Net Change]", "dim_date[week_start] = w")}',
        ]),
        "[In] = [In (pipeline)] && [Done] = [Done (pipeline)] && [Net] = [Net (pipeline)]",
        'FORMAT ( [Week], "yyyy-mm-dd" )',
    )


def section_rows(ref: dict, field: str) -> list[list[str]]:
    return [[text(d), text(s["section"]), number(s[field])]
            for d, v in ref["as_at"].items() for s in v["weeks_to_clear_by_section"]]


SECTION_AT = "VAR d = [As at] VAR s = [Section] RETURN "
SECTION_FILTERS = ("as_at[as_at_date] = d", "dim_section[section] = s")
SECTION_LABEL = 'FORMAT ( [As at], "yyyy-mm-dd" ) & " " & [Section]'


def avg_weekly_completions(ref: dict) -> str:
    return query(
        "Avg Weekly Completions by section",
        "Completions over the four full weeks ending at the as-at date, divided by 4.",
        datatable([("As at", "DATETIME"), ("Section", "STRING"), ("Avg (pipeline)", "DOUBLE")],
                  section_rows(ref, "avg_weekly_completions")),
        f'        "Avg", {SECTION_AT}{at("[Avg Weekly Completions]", *SECTION_FILTERS)} + 0',
        same("[Avg]", "[Avg (pipeline)]"),
        SECTION_LABEL,
    )


def weeks_to_clear(ref: dict) -> str:
    return query(
        "Weeks to Clear by section",
        "Active / Avg Weekly Completions; blank below 5 completions a week.",
        datatable([("As at", "DATETIME"), ("Section", "STRING"), ("WTC (pipeline)", "DOUBLE")],
                  section_rows(ref, "weeks_to_clear")),
        f'        "WTC", {SECTION_AT}{at("[Weeks to Clear]", *SECTION_FILTERS)}',
        same("[WTC]", "[WTC (pipeline)]"),
        SECTION_LABEL,
    )


def contractor_flag(ref: dict) -> str:
    rows = [[text(d), text(s["section"]), "1" if s["flag"] else "0"]
            for d, v in ref["as_at"].items() for s in v["weeks_to_clear_by_section"]]
    counts = [[text(d), text("(Flagged Sections)"), str(len(v["flagged_sections"]))]
              for d, v in ref["as_at"].items()]
    return query(
        "Contractor Flag and Flagged Sections",
        "Every section at the default threshold of 3 weeks, and the count of flagged sections per date.",
        datatable([("As at", "DATETIME"), ("Section", "STRING"), ("Flag (pipeline)", "INTEGER")], rows + counts),
        f'        "Flag", {SECTION_AT}IF ( s = "(Flagged Sections)", '
        f'{at("[Flagged Sections]", "as_at[as_at_date] = d")}, {at("[Contractor Flag]", *SECTION_FILTERS)} )',
        "[Flag] = [Flag (pipeline)]",
        SECTION_LABEL,
    )


def suburb_rank(ref: dict) -> str:
    rows = []
    for d, v in ref["as_at"].items():
        for section, suburbs in v["suburb_rank_in_flagged_sections"].items():
            for s in suburbs:
                rank = 1 + sum(other["active"] > s["active"] for other in suburbs)  # ties share a rank
                rows.append([text(d), text(section), text(s["official_suburb"]), str(rank),
                             str(s["active"]), number(s["weeks_to_clear"])])
            unknown = v["unknown_suburb_active_in_flagged_sections"][section]
            rows.append([text(d), text(section), text(UNKNOWN_SUBURB), "BLANK ()", str(unknown), "BLANK ()"])
    suburb_filters = (*SECTION_FILTERS, "dim_suburb[suburb] = b")
    return query(
        "Suburb Rank inside flagged sections",
        "Top 10 suburbs by Active in each flagged section, with their Weeks to Clear; "
        "Unknown suburb is never ranked and its Active is reported by Unknown Suburb Active.",
        datatable([("As at", "DATETIME"), ("Section", "STRING"), ("Suburb", "STRING"), ("Rank (pipeline)", "INTEGER"),
                   ("Active (pipeline)", "INTEGER"), ("WTC (pipeline)", "DOUBLE")], rows),
        "\n".join([
            f'        "Rank", VAR d = [As at] VAR s = [Section] VAR b = [Suburb] RETURN '
            f'{at("[Suburb Rank]", *suburb_filters)},',
            f'        "Active", VAR d = [As at] VAR s = [Section] VAR b = [Suburb] RETURN IF ( b = {text(UNKNOWN_SUBURB)}, '
            f'{at("[Unknown Suburb Active]", *SECTION_FILTERS)}, {at("[Active]", *suburb_filters)} ),',
            f'        "WTC", VAR d = [As at] VAR s = [Section] VAR b = [Suburb] RETURN IF ( b = {text(UNKNOWN_SUBURB)}, '
            f'BLANK (), {at("[Weeks to Clear]", *suburb_filters)} )',
        ]),
        f'{same("[Rank]", "[Rank (pipeline)]")} && [Active] = [Active (pipeline)] && {same("[WTC]", "[WTC (pipeline)]")}',
        SECTION_LABEL + ' & " " & [Suburb]',
    )


TESTS = {
    "01-open-active-stuck.dax": open_active_stuck,
    "02-weekly-flow.dax": weekly_flow,
    "03-avg-weekly-completions.dax": avg_weekly_completions,
    "04-weeks-to-clear.dax": weeks_to_clear,
    "05-contractor-flag.dax": contractor_flag,
    "06-suburb-rank.dax": suburb_rank,
}


def main() -> None:
    ref = json.loads(REFERENCE.read_text(encoding="utf-8"))
    OUT.mkdir(parents=True, exist_ok=True)
    for name, build in TESTS.items():
        (OUT / name).write_text(build(ref), encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT) / name}")


if __name__ == "__main__":
    main()
